# ------------------------------------------------------------------------------
# create-site.yml
# ------------------------------------------------------------------------------

---

- hosts: wordpress

  tasks:

    - ansible.builtin.set_fact:
        subdomain: "{{ subdomain }}"

    - ansible.builtin.include_role:
        name: wordpress_apache
        tasks_from: create-site
      when: subdomain in subdomains
      vars:
        subdomains: "{{ wordpress_sites | map(attribute='subdomain') }}"

- hosts: gateway

  # Configure a Dynamic DNS record for the website, since it is hosted on the
  # office network but exposed externally to customer users.  

  tasks:

    - ansible.builtin.import_role:
        name: dynamic_dns
        tasks_from: create-record
      vars:
        wp_host: "{{ groups['wordpress'] | intersect(ansible_limit) | first }}"
        dynamic_dns_record_hostname: "{{ hostvars[wp_host].wp_subdomain }}"
