# ------------------------------------------------------------------------------
# delete-site.yml
# ------------------------------------------------------------------------------

---

- hosts: wordpress

  tasks:

    - name: "\
        Perform tasks that are a common precursor to any WordPress site action"
      ansible.builtin.import_tasks: ./common-tasks/wordpress-action.yml

    # Delete an instance of the website for any particular subdomain on the
    # WordPress server that hosts that instance.

    - ansible.builtin.import_role:
        name: wordpress_apache
        tasks_from: delete-site
      vars:

#- hosts: gateway

#  tasks:

    # Delete a Dynamic DNS record for the website, since it is hosted on the
    # office network but exposed externally to customer users.  

#    - ansible.builtin.import_role:
#        name: dynamic_dns
#        tasks_from: delete-project-records
#      vars:
#        dynamic_dns_records: [ "{{ subdomain }}" ]
