# ------------------------------------------------------------------------------
# install-services.yml
# ------------------------------------------------------------------------------

---

# This playbook creates the base services on the Varilink Computing Ltd hosts.
# Those base services are:
#  - Backup
#  - DNS
#  - Dynamic DNS
#  - Monitor
#  - WordPress
#
# Our hosts play certain roles in the delivery of these services, those roles
# being:
#  - gateway
#  - home
#  - hub
#  - wordpress
#
# Comments below each hosts array element below describe what each role does as
# as result of executing each set of tasks.
#
# Note that these roles are different to the host names, allowing the hosts
# fulfilling a role to be swapped. The gateway, home and hub roles are fulfilled
# by a single host and the mapping is implemented via host aliasing in the
# Ansible inventory. The wordpress role is fulfilled by multiple hosts and the
# mapping is implemented using an group, again in the Ansible inventory.

# ---
# DNS
# ---

- hosts: hub

  # The hub host is the DNS server for the office network. The DNS service must
  # be installed first because other services are dependent on it having been
  # installed before they can install; for example, the backup service can't
  # create a DNS record for the backup web service until the DNS service has
  # installed and created the /etc/addn-hosts file.

  tasks:

    - ansible.builtin.import_role:
        name: dns
      tags: [ backup, monitor, dns ]

# -----------
# Dynamic DNS
# -----------

- hosts: gateway

  tasks:

    - ansible.builtin.import_role:
        name: dynamic_dns
      tags: [ dynamic_dns ]

# ------
# Backup
# ------

- hosts: all:!backup_exceptions

  # All hosts are backed up apart from any that are explicit exceptions.

  tasks:

    - ansible.builtin.import_role:
        name: backup_client
      tags: backup

- hosts: hub

  # The hub host is both the backup director and the backup storage controller.

  tasks:

    - block:

        - ansible.builtin.import_role:
            name: database

        - ansible.builtin.import_role:
            name: database
            tasks_from: create-backup-database

        - ansible.builtin.import_role:
            name: backup_director

        - ansible.builtin.import_role:
            name: backup_storage

      tags: backup

- hosts: home

  # The home host provides the backup dashboard as a web service.

  tasks:

    - block:

        - ansible.builtin.import_role:
            name: backup_web
          vars:
            backup_database_host: "{{ hostvars['hub'].ansible_host }}"

        - block:

            - ansible.builtin.import_role:
                name: database
                tasks_from: create-backup-database
              vars:
                database_user_host: "{{ ansible_hostname }}.{{ domain_name }}"

            - ansible.builtin.import_role:
                name: dns
                tasks_from: create-project-record
              vars:
                dns_record_hostname: backup.{{ home_domain }}

          delegate_to: hub

      tags: backup

# -------
# Monitor
# -------

- hosts: home

  # The home host provides a Grafana monitoring dashboard for all hosts.

  tasks:

    - block:

        - ansible.builtin.import_role:
            name: monitor_server

        - ansible.builtin.import_role:
            name: monitor_dashboard

      tags: monitor

- hosts: gateway

  # The gateway hosts provides a route for all external hosts to send their
  # monitoring data to the home host on the office network.

  tasks:

    - ansible.builtin.import_role:
        name: monitor_gateway
      tags: monitor
      vars:
        env_uses_ca: no

    - ansible.builtin.import_role:
        name: dynamic_dns
        tasks_from: copy-project-records
      tags: monitor

- hosts: all

  # All hosts are monitoring clients, i.e. all hosts are monitored.

  tasks:

    - block:

        - ansible.builtin.import_role:
            name: monitor_server
            tasks_from: get-all-access-token
          delegate_to: home

        - ansible.builtin.import_role:
            name: monitor_client
      
      tags: monitor

# ---------
# WordPress
# ---------

- hosts: wordpress

  # wordpress hosts provide WordPress site hosting services.

  tasks:

    - block:

        - ansible.builtin.import_role:
            name: database

        - ansible.builtin.import_role:
            name: wordpress_apache

        - ansible.builtin.import_role:
            name: reverse_proxy

      tags: wordpress
